name: hotchain
version: 5.2.00
summary:   Hotchain (Blockchain & Cryptocurrency Platform for SouthAsia)
description: |
  HOTCHAIN is an MIT licensed,
  open source, blockchain-based cryptocurrency with 
  ultra fast transactions, low fees, high network decentralization, and
  Zero Knowledge cryptography proofs for industry-leading
  transaction anonymity. 
  
  Download HOTCHAIN White Paper PDF:
    https://hotchain.ams3.digitaloceanspaces.com/docs/Hotchain_Platform_White-Paper-20180524.pdf

grade: devel
confinement: strict

apps:
  daemon:
    command: hotchaind
    plugs: [network, network-bind, home, removable-media]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  daemon-testnet:
    command: hotchaind --testnet
    plugs: [network, network-bind, home, removable-media]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  daemon-regtest:
    command: hotchaind --regtest
    plugs: [network, network-bind, home, removable-media]
  qt:
    command: desktop-launch hotchain-qt
    plugs: [network, network-bind, unity7, unity8-calendar, unity8-contacts, desktop, desktop-legacy, wayland, x11, mir, opengl, home, removable-media]
    desktop: qt.desktop
  qt-testnet:
    command: desktop-launch hotchain-qt --testnet
    plugs: [network, network-bind, unity7, unity8-calendar, unity8-contacts, desktop, desktop-legacy, wayland, x11, mir, opengl, home, removable-media]
    desktop: qt-testnet.desktop
  qt-regtest:
    command: desktop-launch hotchain-qt --regtest
    plugs: [network, network-bind, unity7, unity8-calendar, unity8-contacts, desktop, desktop-legacy, wayland, x11, mir, opengl, home, removable-media]
    desktop: qt-regtest.desktop
  cli:
    command: hotchain-cli
    plugs: [network, network-bind, home, removable-media]
  cli-testnet:
    command: hotchain-cli --testnet
    plugs: [network, network-bind, home, removable-media]
  cli-regtest:
    command: hotchain-cli --regtest
    plugs: [network, network-bind, home, removable-media]
  tx:
    command: hotchain-tx
    plugs: [home]

parts:
  hotchain:
    source: https://github.com/hotchain-project/hotx
    source-type: git
    source-tag: master
    plugin: nil
    override-build: |
      # Patch - Default home folder
      ## We don't want to copy the full blockchain every time that the snap is   
      ## updated, but there's no way to define a default data dir in hotchain-qt.
      ## Additionaly we fix funcs.mk
      git apply $SNAPCRAFT_STAGE/default_data_dir.patch
      git apply $SNAPCRAFT_STAGE/fix-bdb-tmp-folder.patch
      ## Patch - Fix Bug extracting sources without ownership
      sed -i 's/tar --strip-components/tar --no-same-owner --strip-components/' $SNAPCRAFT_PART_BUILD/depends/funcs.mk
      # Build Dependencies
      echo "START BUILDING FOR $SNAPCRAFT_ARCH_TRIPLET architecture"
      cd $SNAPCRAFT_PART_BUILD/depends
      # Fix building ARM and AARCh64, as on some point they fail with, predownload all packages
      #   curl: (22) The requested URL returned error: 407
      make download-linux
      if [ $SNAPCRAFT_ARCH_TRIPLET = "i386-linux-gnu" ]
      then
        make HOST=i686-linux-gnu
      else
        make HOST=$SNAPCRAFT_ARCH_TRIPLET
      fi
      # Configure Ion Core
      cd $SNAPCRAFT_PART_BUILD
      ./autogen.sh
      if [ $SNAPCRAFT_ARCH_TRIPLET = "i386-linux-gnu" ]
      then
        ./configure --prefix=`pwd`/depends/i686-linux-gnu
      else
        ./configure --prefix=`pwd`/depends/$SNAPCRAFT_ARCH_TRIPLET
      fi
      # Compile Ion Core
      make
      # Install Ion Core
      make install prefix=$SNAPCRAFT_PART_INSTALL
      # print in log which files are installed
      echo "Installed files:"
      ls $SNAPCRAFT_PART_INSTALL
    # Fix: You need multipass installed to build snaps which use the base keyword.
    build-packages:
      - curl
      - wget
      - g++
      - gcc
      - make
      - autoconf
      - automake
      - cmake
      - pkg-config
      - libtool
      - bsdmainutils
      - binutils
      - python3
    stage-packages: [ca-certificates]
    after:
      - desktop-qt5
      - patches
  desktop-qt5:
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
      - qtwayland5
  patches:
    source: snap/patches
    plugin: dump
    prime:
      - -*
  desktop:
    source: snap/usr/share/applications
    plugin: dump
